### ISSUE TITLE
Windows 8.1 - The specified procedure could not be found

### ISSUE THREAD

**Issue by lech206** [s1hofmann/native-ui-toolkit#408]
When I try run application which use nut.js 2.x (2.0.0 - 2.1.1) on Windows 8.1  I get "Error: The specified procedure could not be found."
Everything is ok on Windows 10.

Problem is similar to [#397](url)

**Desired execution environment / tested on**
- [x] Dev/Host system

Node v16.15.1
NPM 8.11.0

**Detailed question**

```
C:\Users\admin\Downloads\test-nut-js\node_modules\bindings\bindings.js:121
        throw e;
        ^

Error: Nie mo?na odnale?a okre?lonej procedury.
\\?\C:\Users\admin\Downloads\test-nut-js\node_modules\@nut-tree\libnut-win32\build\Release\libnut.node
    at Object.Module._extensions..node (node:internal/modules/cjs/loader:1189:18)
    at Module.load (node:internal/modules/cjs/loader:981:32)
    at Function.Module._load (node:internal/modules/cjs/loader:822:12)
    at Module.require (node:internal/modules/cjs/loader:1005:19)
    at require (node:internal/modules/cjs/helpers:102:18)
    at bindings (C:\Users\admin\Downloads\test-nut-js\node_modules\bindings\bindings.js:112:48)
    at Object.<anonymous> (C:\Users\admin\Downloads\test-nut-js\node_modules\@nut-tree\libnut-win32\index.js:1:35)
    at Module._compile (node:internal/modules/cjs/loader:1105:14)
    at Object.Module._extensions..js (node:internal/modules/cjs/loader:1159:10)
    at Module.load (node:internal/modules/cjs/loader:981:32) {
  code: 'ERR_DLOPEN_FAILED'
}
```
If I use mixed enviroment Windows 8.1 / 10 / 11 can I use version 2.x ?
Older version nut-js 1.7.0 work on Windows 8.1.

Reproduce error

package.json
`
{
  "name": "test-nut",
  "version": "1.0.0",
  "description": "",
  "main": "index.js",
  "scripts": {
    "test": "echo \"Error: no test specified\" && exit 1"
  },
  "keywords": [],
  "author": "",
  "license": "ISC",
  "dependencies": {
    "@nut-tree/nut-js": "^2.1.1"
  }
}
`

index.js
`
const { keyboard } = require('@nut-tree/nut-js');
`

**Comment by s1hofmann** [comment]
Hi @lech206 👋 

nut.js is only built and tested against Windows 10.
Given that Windows 8.1 will reach its extended lifecycle EOL I'm not considering this for changes.

Best regards

Simon
