### ISSUE TITLE
Error: Failed to capture screen

### ISSUE THREAD

**Issue by nickthorp1** [s1hofmann/native-ui-toolkit#584]
**Version**
    "@nut-tree/nl-matcher": "^3.0.1",
    "@nut-tree/nut-js": "^4.2.1-next.20240411081530",
    "@nut-tree/plugin-ocr": "^2.0.1",
**Short overview**

I am unable to access the screen, eventho I have given permissions in my settings
![Screenshot 2024-04-15 at 13 26 27](https://github.com/nut-tree/nut.js/assets/95623634/04ad25da-cba7-474e-ba3e-c5f6131feb3f)

**Issue occurs on**

- [ ] Virtual machine
- [ ] Docker container
**- [ ] Dev/Host system**

**node version**:
v18.19.0 (npm v10.2.3)
**OS type and version**:
Mac M3, Sonoma V 14.2
**Detailed error description**

Error: Error: Failed to capture screen
    at libnut.<computed> (/Users/nicholasthorp/Documents/code/nutzv4/node_modules/@nut-tree/libnut-darwin/permissionCheck.js:70:96)
    at Object.libnut.<computed> [as captureScreen] (/Users/nicholasthorp/Documents/code/nutzv4/node_modules/@nut-tree/libnut-darwin/permissionCheck.js:74:98)
    at Object.module.exports.screen.capture (/Users/nicholasthorp/Documents/code/nutzv4/node_modules/@nut-tree/libnut-darwin/index.js:38:20)
    at /Users/nicholasthorp/Documents/code/nutzv4/node_modules/@nut-tree/nut-js/node_modules/@nut-tree/libnut/dist/lib/libnut-screen.class.js:29:62
    at new Promise (<anonymous>)
    at ScreenAction.grabScreenRegion (/Users/nicholasthorp/Documents/code/nutzv4/node_modules/@nut-tree/nut-js/node_modules/@nut-tree/libnut/dist/lib/libnut-screen.class.js:28:16)
    at ScreenClass.grabRegion (/Users/nicholasthorp/Documents/code/nutzv4/node_modules/@nut-tree/nut-js/dist/lib/screen.class.js:374:14)
    at async ScreenClass.readText [as read] (/Users/nicholasthorp/Documents/code/nutzv4/node_modules/@nut-tree/plugin-ocr/dist/src/readText.function.js:18:50)
    at async file:///Users/nicholasthorp/Documents/code/nutzv4/fullProfile.js:13:18
(base) Nicks-MacBook-Pro:nutzv4 nicholasthorp$ 

**Full code sample to reproduce**

import {getActiveWindow, screen} from "@nut-tree/nut-js";
import {configure, Language, LanguageModelType, TextSplit, preloadLanguages} from "@nut-tree/plugin-ocr";

const activeWindowRegion = async () => {
    const activeWindow = await getActiveWindow();
    return activeWindow.region;
}

(async () => {
    // await preloadLanguages([Language.English]);
    const text = await screen.read({searchRegion: activeWindowRegion(), split: TextSplit.LINE});
    console.log(text)
})();

**Additional content**

> Please provide any (mandatory) additional data to reproduce the error (Dockerfiles etc.)

**Comment by s1hofmann** [comment]
Hi @nickthorp1 👋 

Does this happen on each an every try to access screen content?
Something like `screen.capture` etc?

Can you enable log output using

```js
import { useConsoleLogger, ConsoleLogLevel } from "@nut-tree/nut-js";

useConsoleLogger({ logLevel: ConsoleLogLevel.DEBUG });
```

Best regards

Simon

**Comment by nickthorp1** [comment]
Hi Simon thank you for the help, 

I am able to successfully taker screenshots using capture and capture region, I believe the issue may arise only in the @nut-tree/plugin-ocr package.

I am implementing use-Logger correctly, searched the docs but coudn't see the correct usage?
```

import {getActiveWindow, screen, useConsoleLogger, ConsoleLogLevel } from "@nut-tree/nut-js";
import {configure, Language, LanguageModelType, TextSplit, preloadLanguages} from "@nut-tree/plugin-ocr";
useConsoleLogger({ logLevel: ConsoleLogLevel.DEBUG });
const activeWindowRegion = async () => {
const activeWindow = await getActiveWindow();
return activeWindow.region;
}

(async () => {
// await preloadLanguages([Language.English]);
const text = await screen.read({searchRegion: activeWindowRegion(), split: TextSplit.LINE});
console.log(text)


})();
```


**output**

(base) Nicks-MacBook-Pro:fullProfile nicholasthorp$ node screenCapture.js 
2024-04-16T07:07:10.873Z - INFO - [nut.js] - Active window handle { windowHandle: 142 }
2024-04-16T07:07:10.877Z - INFO - [nut.js] - Reading text from screen at location (0, 0, 0, 982)
/Users/nicholasthorp/Documents/code/nutzv4/node_modules/@nut-tree/libnut-darwin/permissionCheck.js:70
        libnut[functionName] = (...args) => askForAccessibility(originalFunction, functionName)(...args);
                                                                                               ^

Error: Error: Failed to capture screen
    at libnut.<computed> (/Users/nicholasthorp/Documents/code/nutzv4/node_modules/@nut-tree/libnut-darwin/permissionCheck.js:70:96)
    at Object.libnut.<computed> [as captureScreen] (/Users/nicholasthorp/Documents/code/nutzv4/node_modules/@nut-tree/libnut-darwin/permissionCheck.js:74:98)
    at Object.module.exports.screen.capture (/Users/nicholasthorp/Documents/code/nutzv4/node_modules/@nut-tree/libnut-darwin/index.js:38:20)
    at /Users/nicholasthorp/Documents/code/nutzv4/node_modules/@nut-tree/nut-js/node_modules/@nut-tree/libnut/dist/lib/libnut-screen.class.js:29:62
    at new Promise (<anonymous>)
    at ScreenAction.grabScreenRegion (/Users/nicholasthorp/Documents/code/nutzv4/node_modules/@nut-tree/nut-js/node_modules/@nut-tree/libnut/dist/lib/libnut-screen.class.js:28:16)
    at ScreenClass.grabRegion (/Users/nicholasthorp/Documents/code/nutzv4/node_modules/@nut-tree/nut-js/dist/lib/screen.class.js:374:14)
    at async ScreenClass.readText [as read] (/Users/nicholasthorp/Documents/code/nutzv4/node_modules/@nut-tree/plugin-ocr/dist/src/readText.function.js:18:50)
    at async file:///Users/nicholasthorp/Documents/code/nutzv4/fullProfile/screenCapture.js:11:14
(base) Nicks-MacBook-Pro:fullProfile nicholasthorp$

**Comment by nickthorp1** [comment]
Hi Simon, Thanks for you help.

So I can able to captureRegion successfully, the code below successfully produces  2 screenshots

```
import {getActiveWindow, screen, useConsoleLogger, ConsoleLogLevel } from "@nut-tree/nut-js";
import {configure, Language, LanguageModelType, TextSplit, preloadLanguages} from "@nut-tree/plugin-ocr";
useConsoleLogger({ logLevel: ConsoleLogLevel.DEBUG });
const activeWindowRegion = async () => {
const activeWindow = await getActiveWindow();
return activeWindow.region;
}

(async () => {
// await preloadLanguages([Language.English]);
const test1 = await screen.capture('test1')
const coor = new Region(245, 190, 750, 790);
const test2 = await screen.captureRegion(
    `test2`,
    coor,
);
const text = await screen.read({searchRegion: activeWindowRegion(), split: TextSplit.LINE});
console.log(text)


})();
```

**Output**
(base) Nicks-MacBook-Pro:fullProfile nicholasthorp$ node screenCapture.js 
2024-04-16T07:19:51.445Z - INFO - [nut.js] - Capturing whole screen (0, 0, 3024, 1964)
2024-04-16T07:19:51.446Z - INFO - [nut.js] - Writing image to /Users/nicholasthorp/Documents/code/nutzv4/fullProfile/test1.png
2024-04-16T07:19:51.873Z - DEBUG - [nut.js] - File written
2024-04-16T07:19:51.873Z - INFO - [nut.js] - Capturing screen region (245, 190, 750, 790)
2024-04-16T07:19:51.886Z - INFO - [nut.js] - Writing image to /Users/nicholasthorp/Documents/code/nutzv4/fullProfile/test2.png
2024-04-16T07:19:52.039Z - DEBUG - [nut.js] - File written
2024-04-16T07:19:52.042Z - INFO - [nut.js] - Active window handle { windowHandle: 142 }
2024-04-16T07:19:52.044Z - INFO - [nut.js] - Reading text from screen at location (0, 0, 0, 982)
/Users/nicholasthorp/Documents/code/nutzv4/node_modules/@nut-tree/libnut-darwin/permissionCheck.js:70
        libnut[functionName] = (...args) => askForAccessibility(originalFunction, functionName)(...args);
                                                                                               ^

Error: Error: Failed to capture screen
    at libnut.<computed> (/Users/nicholasthorp/Documents/code/nutzv4/node_modules/@nut-tree/libnut-darwin/permissionCheck.js:70:96)
    at Object.libnut.<computed> [as captureScreen] (/Users/nicholasthorp/Documents/code/nutzv4/node_modules/@nut-tree/libnut-darwin/permissionCheck.js:74:98)
    at Object.module.exports.screen.capture (/Users/nicholasthorp/Documents/code/nutzv4/node_modules/@nut-tree/libnut-darwin/index.js:38:20)
    at /Users/nicholasthorp/Documents/code/nutzv4/node_modules/@nut-tree/nut-js/node_modules/@nut-tree/libnut/dist/lib/libnut-screen.class.js:29:62
    at new Promise (<anonymous>)
    at ScreenAction.grabScreenRegion (/Users/nicholasthorp/Documents/code/nutzv4/node_modules/@nut-tree/nut-js/node_modules/@nut-tree/libnut/dist/lib/libnut-screen.class.js:28:16)
    at ScreenClass.grabRegion (/Users/nicholasthorp/Documents/code/nutzv4/node_modules/@nut-tree/nut-js/dist/lib/screen.class.js:374:14)
    at async ScreenClass.readText [as read] (/Users/nicholasthorp/Documents/code/nutzv4/node_modules/@nut-tree/plugin-ocr/dist/src/readText.function.js:18:50)
    at async file:///Users/nicholasthorp/Documents/code/nutzv4/fullProfile/screenCapture.js:17:14
(base) Nicks-MacBook-Pro:fullProfile nicholasthorp$

**Comment by nickthorp1** [comment]
![Screenshot 2024-04-16 at 08 21 41](https://github.com/nut-tree/nut.js/assets/95623634/a88ad338-c092-4810-916b-3e4e95d2d0ad)

**Comment by s1hofmann** [comment]
Hi @nickthorp1 👋 

The log tells us that it's related to the active window region:

> Reading text from screen at location (0, 0, 0, 982)

The window dimensions are messed up. Which kind of window are you targeting?

**Comment by nickthorp1** [comment]
Hi Simon,

I have a monitor and a 14inch Mac M3, I think it was because I was using a monitor. Is there away to use both so I can have the code on the monitor and my mac as the active window?

**Comment by s1hofmann** [comment]
It’ll work as long as your automation runs on the main screen.
nut.js currently only supports a single screen (the main one), so this has to be ensured.
Your code would be on the second screen.

Edit: Since this is actually working as documented I’d close this issue

**Comment by nickthorp1** [comment]
Great thank you for the help with this!

**Comment by s1hofmann** [comment]
@nickthorp1 If you want to make sure the window is always located within the main screen area you could simply move the window to position (0,0) which is defined to be the upper left corner of the main screen.
