### ISSUE TITLE
Minimum/Maximum Screen Dimensions Error

### ISSUE THREAD

**Issue by ghost** [s1hofmann/native-ui-toolkit#588]
**Short summary**
I'm seeing an error when providing a search region to the `screen.find(singleWord())` function.

**Desired execution environment / tested on**
- [ ] Virtual machine
- [ ] Docker container
- [x] Dev/Host system

**node version**:
20.11.1

**OS type and version**:
Windows 11

**Full code sample related to question**
```javascript
const nut = require('@nut-tree/nut-js');
const azure = require('@nut-tree/plugin-azure/ocr');
const { api_data } = require('./azure-config');
require('@nut-tree/nl-matcher');

azure.configure({
    apiKey: api_data.API_KEY,
    apiEndpoint: api_data.API_ENDPOINT,
    language: azure.Language.English
});
azure.useAzureVisionOCR();

(async () => {
    try {
        nut.sleep(1000);
        let topCenter = new nut.Region(0, 0, 1920, 35);
        nut.screen.highlight(topCenter);
        let searchParams = {
            searchRegion: topCenter,
            providerData: {
                partialMatch: true
            }
        }
        let result = await nut.screen.find(nut.textLine('ProPresenter'), searchParams);
        nut.screen.highlight(result);
    } catch (err) {
        console.error(err);
        await nut.mouse.move(new nut.Point(960, 540));
    }
})();
```

**Detailed question**
Trying to find some text in the top part of the screen. My resolution is 1920x1080.
I'm using Azure OCR.

If I change the search region height to 50, it works.
My question is: is this an Azure error message or a nut.js one?
And if it's a nut.js one, why is it showing only on Windows (this error hasn't appeared on Mac).

```
Error: [nut.js] - Error: Searching for word-query-ProPresenter failed. 
Reason: 'Error: OCR run failed. Reason: Error: The input image dimension is out of range. 
The minimum image/document page dimension is 50 x 50 pixels 
and the maximum is 10000 x 10000 pixels. The maximum PDF dimension is 17 x 17 inches.'
    at ScreenClass.find (C:\Users\---\nut-js-testing\node_modules\@nut-tree\nut-js\dist\lib\screen.class.js:158:27)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
    at async C:\Users\---\nut-js-testing\scripts\interactions.js:168:28
```

**Comment by ghost** [comment]
Answers found in Discord:
- This is an Azure error message
- The reason it was showing on Win and not Mac was that my mac was set to a HiDPI 1080p (actual resolution 4k), whereas the windows was set to an actual 1080p resolution
